[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "data"]

reportMissingImports = "warning"
reportMissingTypeStubs = false
reportPrivateImportUsage = false

[tool.isort]
profile = "hug"
skip = [".gitignore"]
length_sort = true
lines_between_sections = 0
lines_after_imports = 1
